### ISSUE TITLE
Spam Mails are not deleted after processing

### ISSUE THREAD

**Issue by Manuel1948** [magenbrot/sa_learn_from_imap#1]
Hi,

I don't know if this is normal but the mails from the spam folder are not deleted after processing like the mails from ham folder...

**Comment by magenbrot** [comment]
This script handles ham and spam mails in the same way (same function). After they've been fetched and saved on disk it will set the "DELETED" flag in imap. I can't say why this is not working.

**Comment by Manuel1948** [comment]
> This script handles ham and spam mails in the same way (same function). After they've been fetched and saved on disk it will set the "DELETED" flag in imap. I can't say why this is not working.

Hi magenbrot,

today I checked the IMAP logs of my exchange server.
You can check whats going on and according to a recommendation from Pavel Cernik at the following page:
https://www.php.net/manual/de/function.imap-expunge.php#119264
I found out how to fix this problem.

`
select,spam,"R=OK;Rows=50
search,ALL,"R=OK;Rows=50
fetch,1 (RFC822),"R=OK;Rows=1
store,1 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,2 (RFC822),"R=OK;Rows=1
store,2 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,3 (RFC822),"R=OK;Rows=1
store,3 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,4 (RFC822),"R=OK;Rows=1
store,4 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,5 (RFC822),"R=OK;Rows=1
store,5 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,6 (RFC822),"R=OK;Rows=1
store,6 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,7 (RFC822),"R=OK;Rows=1
store,7 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,8 (RFC822),"R=OK;Rows=1
store,8 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,9 (RFC822),"R=OK;Rows=1
store,9 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,10 (RFC822),"R=OK;Rows=1
store,10 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,11 (RFC822),"R=OK;Rows=1
store,11 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,12 (RFC822),"R=OK;Rows=1
store,12 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,13 (RFC822),"R=OK;Rows=1
store,13 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,14 (RFC822),"R=OK;Rows=1
store,14 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,15 (RFC822),"R=OK;Rows=1
store,15 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,16 (RFC822),"R=OK;Rows=1
store,16 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,17 (RFC822),"R=OK;Rows=1
store,17 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,18 (RFC822),"R=OK;Rows=1
store,18 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,19 (RFC822),"R=OK;Rows=1
store,19 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,20 (RFC822),"R=OK;Rows=1
store,20 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,21 (RFC822),"R=OK;Rows=1
store,21 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,22 (RFC822),"R=OK;Rows=1
store,22 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,23 (RFC822),"R=OK;Rows=1
store,23 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,24 (RFC822),"R=OK;Rows=1
store,24 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,25 (RFC822),"R=OK;Rows=1
store,25 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,26 (RFC822),"R=OK;Rows=1
store,26 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,27 (RFC822),"R=OK;Rows=1
store,27 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,28 (RFC822),"R=OK;Rows=1
store,28 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,29 (RFC822),"R=OK;Rows=1
store,29 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,30 (RFC822),"R=OK;Rows=1
store,30 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,31 (RFC822),"R=OK;Rows=1
store,31 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,32 (RFC822),"R=OK;Rows=1
store,32 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,33 (RFC822),"R=OK;Rows=1
store,33 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,34 (RFC822),"R=OK;Rows=1
store,34 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,35 (RFC822),"R=OK;Rows=1
store,35 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,36 (RFC822),"R=OK;Rows=1
store,36 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,37 (RFC822),"R=OK;Rows=1
store,37 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,38 (RFC822),"R=OK;Rows=1
store,38 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,39 (RFC822),"R=OK;Rows=1
store,39 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,40 (RFC822),"R=OK;Rows=1
store,40 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,41 (RFC822),"R=OK;Rows=1
store,41 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,42 (RFC822),"R=OK;Rows=1
store,42 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,43 (RFC822),"R=OK;Rows=1
store,43 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,44 (RFC822),"R=OK;Rows=1
store,44 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,45 (RFC822),"R=OK;Rows=1
store,45 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,46 (RFC822),"R=OK;Rows=1
store,46 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,47 (RFC822),"R=OK;Rows=1
store,47 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,48 (RFC822),"R=OK;Rows=1
store,48 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,49 (RFC822),"R=OK;Rows=1
store,49 +FLAGS (\Deleted),"R=OK;Rows=1
fetch,50 (RFC822),"R=OK;Rows=1
store,50 +FLAGS (\Deleted),"R=OK;Rows=1


select,ham,"R=OK;Rows=1
search,ALL,"R=OK;Rows=1
fetch,1 (RFC822),"R=OK;Rows=1
store,1 +FLAGS (\Deleted),"R=OK;Rows=1
expunge,,"R=OK;Rows=1
close,,"R=OK;
logout,,"R=OK;
`

In the logs I see that of the two commands (select/search) is also resetting the mail-number which is represented at the fetch/store commands (spam folder is counting to 50 and then if you process the next folder (ham) the id starts again from 1, which is the problem). 

So if you follow the advice from Pavel Cernik you need to expunge the mails before the next process-command in you script. So that means if you add a  "mail.expunge()" at line 92 (between the two folder-processings) the problem is solved and your script works like it should.

Kind regards,
Manuel1948

**Comment by Manuel1948** [comment]
Please close this issue when you fixed the code :)

**Comment by magenbrot** [comment]
thank you @Manuel1948
